name: Command Runner
description: "A plugin to run a specified command. Useful if commands are needed prior to other plugins running."
author: viviedu
requirements:
 - bash
configuration:
  properties:
    precheckout:
      type: string
    checkout:
      type: string
    postcheckout:
      type: string
  additionalProperties: false
hooks:
  post-checkout: hooks/post-checkout