name: Command Runner
description: "A plugin to run a specified command at any of the checkout steps"
author: viviedu
requirements:
 - bash
configuration:
  properties:
    precheckout:
      type: string
    checkout:
      type: string
    postcheckout:
      type: string
  additionalProperties: false
hooks:
  pre-checkout: hooks/pre-checkout
  checkout: hooks/checkout
  post-checkout: hooks/post-checkout