name: "command-runner-buildkite-plugin"
description: "A plugin to run a specified command. Useful if commands are needed prior to other plugins running."
author: "viviedu"
configuration:
  properties:
    command:
      type: string
  additionalProperties: false
hooks:
  pre-checkout: hooks/pre-checkout