#!/bin/bash
set -euo pipefail

echo "--- running pre checkout command"

command="${BUILDKITE_PLUGIN_COMMAND_RUNNER_PRECHECKOUT:-}"

if [ -z "$command" ]; then
  echo "No command specified. Skipping."
else
  echo "Running command: $command"
  eval "$command"
fi

echo "--- finished running pre checkout command"