#!/usr/bin/env bash
set -euo pipefail

echo "--- running command"

command="$(plugin_read_config COMMAND)"

if [ -z "$command" ]; then
  echo "No command specified. Skipping."
else
  echo "Running command: $command"
  eval "$command"
fi

echo "--- finished running command"